name=input("Enter the name: ")
age=int(input("Enter the age: "))
course=input("Enter the course: ")
contact_no=int(input("Enter contact number: "))
print("\n")
print("Name is:" ,name)
print("Age is: " ,age)
print("Course is: ",course)
print("Contact number: " ,contact_no)